WebApplication1/Models/ErrorViewModel.cs
using System;

namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/Koltso.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Koltso
    {
        public double R1 { get; set; }
        public double r { get; set; }
        public double S { get; set; }
        public const double pi = 3.14;
    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Controllers/KoltsoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class KoltsoController : Controller
    {
        public IActionResult Koltso([FromQuery] Koltso request)
        {
            request.S = LibKoltso.Class1.Koltso(request.R1, request.r);
            return View(request);
        }
    }
}

WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "RaschetSquareRing List";
}

<h2>RaschetSquareRing List</h2>
<div class="text-center">
    <h1 class="display-4">Расчёт площади кольца</h1>
    <img class="item_work_bg lazy" src="~/images/1407974009_ploschad-kolca.jpg" alt="Formula">
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication1/Views/Koltso/Koltso.cshtml
@model WebApplication1.Models.Koltso
@{
}
<html>
<head>
    <title>Площадь кольца</title>
</head>
<body>
    <h1>Вычисление площади кольца</h1>
    <form class="row" action="/Koltso/Koltso" align="center">
        <div class="form-group">
            <label for="r">Внутрений радиус</label>
            <input name="r" type="number" class="form-control" id="r" value="@Model.r" />
        </div>
        <div class="form-group">
            <label for="R1">Внешний радиус</label>
            <input name="R1" type="number" class="form-control" id="R1" value="@Model.R1" />
        </div>
        <div align="center">
            <button type="submit" class="btn btn-default" id="Square">Посчитаем</button>
        </div>
        <div class="form-group">
            <label for="S">Площадь кольца</label>
            <input type="text" class="form-control" id="S" value="@Model.S" />
        </div>
    </form>
</body>
</html>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RaschetSquareRing</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RaschetSquareRing</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Koltso" asp-action="Koltso">Koltso</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - RaschetSquareRing - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>